version: "3.9"
services:
  mlops-api:
    image: mlops-bc:latest
    build: .
    container_name: mlops_api
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: INFO
      MODEL_PATH: model.joblib
    restart: unless-stopped
